### ISSUE TITLE
iPhone 7 ApNonce without Jailbreak

### ISSUE THREAD

**Issue by miroccur** [tihmstar/tsschecker#20]
While saving shsh2 for iPhone 7, iOS 10.2, it told me to manually specify an apnonce with len=32, the problem is how can I get an apnonce on unjailbroken device?

**Comment by tihmstar** [comment]
This is a workaround, because currently the algorithm to dervice apnonce from generator is unknown. 
For *just* saving you shsh files you can use
--apnonce AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Apnonce doesn't really matter. 
This shsh file won't be usable with prometheus because you won't be able to regenerate this nonce (because we don't know generator) but it will probably be fine for different downgrade methods.
I'm working on an update for tsschecker to save generator for iPhone7
