### ISSUE TITLE
Is this error expected for iPhone 7?(bbgcid)

### ISSUE THREAD

**Issue by miroccur** [tihmstar/tsschecker#27]
[Error] [TSSC] ERROR: device "iPhone9,1" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet.
[WARNING] [TSSR] WARNING: there was an error getting BasebandGoldCertID, continuing without requesting Baseband ticket

**Comment by tihmstar** [comment]
Yes. You can get more information here: http://blog.tihmstar.net/2017/01/basebandgoldcertid-not-found-please.html
For iPhone9,1 i think there is a bug somewhere. To figure this out i need to see a working tssrequest. Since i don't own this device i can't fix this unless someone sends me a working baseband tssrequest (preferebly via email)

**Comment by miroccur** [comment]
May I know how I can get full log of tssrequest for this model? I would like to help.

Also, could you please look at this tsschecker question? I am really confused. https://github.com/tihmstar/noncestatistics/issues/5
