### ISSUE TITLE
When saving iOS 10.2.1 with iPhone8,2 N66mAP an issue occurs.

### ISSUE THREAD

**Issue by Dorno** [tihmstar/tsschecker#46]
When saving iOS 10.2.1 with iPhone8,2 N66mAP an issue occurs.

The issue is that when you 'check' the blob via https://tsssaver.1conan.com/ it says the file is valid, BUT, instead of listing N66mAP as the build it lists n56ap, which obviously is the build for the iPhone 6+, not the 6s+.

Is this an issue or just a typo or something? Is it currently possible to save the 10.2.1 blobs for an iPhone 6s+? 

Thanks for taking the time to read this and hopefully I'm not wasting your time.

**Comment by derobi** [comment]
have you tried to use the img4tool by tihmstar just in case tsssaver.1 is not valid
you will need to download the ipsw for the file and extract the BuildManifest.plist file..
in order to validate the blob you will have to run this command ./img4tool -v BuildManifest.plist -s then your blob

img4tool can be found by click this link 
http://api.tihmstar.net/builds/img4tool/img4tool-latest.zip

**Comment by Dorno** [comment]
The blobs I had created before were in fact the wrong build, but, I was unknowingly using an older version of tsschecker that came with a batch file. Even when using the program w/o the batch file I still had the issue of the wrong build number.

I d/l the latest version of tsschecker and for some odd reason I got an error that the program was unable to d/l the .plist file and therefore I saw an error that 10.2 & 10.2.1 were no longer being signed.

So, I decided to try tsssaver website again and it worked and generated blobs with the proper build number, just as it did yesterday. Except yesterday I only received blobs for 10.2 and now today the site generated blobs for both 10.2 and 10.2.1

I'm not really sure what caused the issue, but, it's fixed now either way and I have blobs for the currently signed versions of iOS.  Thanks for your help.
