### ISSUE TITLE
Failed to download Build Manifest

### ISSUE THREAD

**Issue by CyberiumShadow** [tihmstar/tsschecker#47]
![image](https://cloud.githubusercontent.com/assets/4259904/22276381/532d0a8e-e307-11e6-84eb-f634425ed36e.png)

**Comment by CyberiumShadow** [comment]
This is on Windows @tihmstar

**Comment by vlldk** [comment]
Yea I get the same error on windows with iPhone7,2 on iOS 10.2. the following message is "iOS 10.2 for device iPhone7,2 IS NOT being signed!" even though it is. I tried to follow the link tsschecker displayed, for fun, and gave me a 10.2 downloadfile.

**Comment by tihmstar** [comment]
Can you provide full log or screenshot?
Otherwise i can't help you

**Comment by vlldk** [comment]
![image](https://cloud.githubusercontent.com/assets/25381970/22397801/fd21420c-e579-11e6-81ee-39c2243f5cea.png)

Sure:

**Comment by PwnK** [comment]
Have you found any fix for this yet? I'm having this same problem except it says:
[Error] [LFZP] failed to download file (-10)

**Comment by tihmstar** [comment]
Something is broken with recent libfragmentzip builds on windows. Might be related to my compiler changes.

**Comment by ShunKun** [comment]
I am using the latest version also encountered this problem, but I used the old version resolved.
New version (no work) -> old version (work) -> new version (work)
Old version: Version: ae684cc90750d1abc10842a34e2615ba47fc8e0c - 154
New version: Version: 1f0dcf714dbcd0b01431d6b87030fe1573ec50e0 - 209

This is using Google Translate. Thank you for your work.

**Comment by q158073378252010** [comment]
Version 212 also has this problem! Then the amount of 170 version is not.
System: win2008r2

**Comment by PwnK** [comment]
Your shsh2 file is only 8KB probably because you didn't save the baseband ticket. If you want to use newer versions of tsschecker you have to use linux vm because I don't think tihmstar is fixing the windows support any time soon.

**Comment by q158073378252010** [comment]
@PwnK 
How do I run version 212 in debian? 
How can i save a base with shsh2?
Has the baseband shsh2 and no baseband shsh2 What is the difference?

**Comment by mrdc** [comment]
Confirm:
`Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[Error] [LFZP] failed to download file (-10)
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://appldnl
d.apple.com/ios10.3/091-02974-20170327-75848B3A-0D86-11E7-8DD8-92CE122AC769/iPho
ne_4.0_32bit_10.3_14E277_Restore.ipsw

iOS 10.3 for device iPhone5,1 IS NOT being signed!`
on Win7x64

**Comment by OothecaPickleGNUrmsTUXFSF** [comment]
Until this bug is fixed you can use the "-m" parameter and manually download IPSW's and extract BuildManifest's from them.

**Comment by turlodales** [comment]
im having the same problems everything is working on 170 but any other verson it keeps saying not being signed.

**Comment by leandroprz** [comment]
I've experienced this same issue since January/February I think. I fixed it by using the ipsw's BuildManifest.plist with -m.

**Comment by turlodales** [comment]
Thank you both of the help


I have manage to save them using my mac and all saving fine on ver216 as i spent hours trying to get use it with out keep getting errors found out if was my dislexic part kicking in and found out i was baking a simple error and not adding ./ at the start i sorry im still a noob to mac have had it over 4years and still not using it to is full use pour macmini needs a better user but it is stuck with me now im out of work after 4 years only getting 2 days off each week so i only had one day to use it after sleeping due to working nights this is why my app is taking so long due to me saved shsh blobs 10.2.1 upto 10.3.2 beta did notice i cant save 10.3.1 blobs but still cant use ver216 on my pc and ver170 on pc and ver216 that i was not able to save my 10.3.1 blobs just keeps not being signed


keep up the very good work


________________________________

**Comment by pedro-mendonca** [comment]
I can't save my SHSH2 for iPad6,11 with the latest version, but did it with v170 in Windows

**Comment by q158073378252010** [comment]
@pedro-mendonca 需要使用 liunx or mac

**Comment by pedro-mendonca** [comment]
@q158073378252010 I'm on Windows 10

**Comment by q158073378252010** [comment]
我不知道

**Comment by CyberiumShadow** [comment]
I believe this can be closed now, due to the recent versions of tsschecker.

Feel free to create a new issue if this persists

**Comment by N1Chris** [comment]
It has come back up again. It is still not working.

C:\Users\Chris\Documents\Flight Simulator X Files\Jailbreak\Tsschecker>tsschecker_windows.exe -d iPhone4,1 -e 2222C0983C9 -i 6.1.3 -o -s
Version: 7d267698cb16ab4699fa9cba20783ee041ac999e - 212
[TSSC] manually specified ecid to use, parsed "2222C0983C9" to dec:2345790964681 hex:2222c0983c9
[TSSC] opening ota.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 6.1.3 build 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] skipping duplicated buildid 10B329
[TSSC] opening Buildmanifest for iPhone4,1_6.1.3_10B329ota
[LFZP] downloading AssetData/boot/BuildManifest.plist from http://appldnld.apple.com/iOS6.1/091-3360.20130311.BmfR4/com_apple_MobileAsset_SoftwareUpdate/fed59972bbaf5105b0fde520f36428f6078d5961.zip

[A[J100 [===================================================================================================>]
[A[J028 [===========================>                                                                        ]
[A[J100 [===================================================================================================>]
[Error] [LFZP] failed to download file (-10)
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://appldnld.apple.com/iOS6.1/091-3360.20130311.BmfR4/com_apple_MobileAsset_SoftwareUpdate/fed59972bbaf5105b0fde520f36428f6078d5961.zip

**Comment by Xerotherm1c** [comment]
Also happening for me on Windows 10. I had to download firmware.json manually because that was erroring out, but I'm still getting "[LFZP] failed to download file (-10)"

Cmd: tsschecker_windows -d iPhone8,1 -e [ECID] -i 11.4.1 --buildid 15G77 -s

[TSSC] got firmwareurl for iOS 11.4.1 build 15G77
[TSSC] opening Buildmanifest for iPhone8,1_11.4.1_15G77
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2018/ios/091-74855-20180709-81396E0E-7C1C-11E8-A003-A75B544C24EB/iPhone_4.7_11.4.1_15G77_Restore.ipsw

[A[J100 [===================================================================================================>]
[A[J033 [================================>                                                                   ]
[A[J071 [======================================================================>                             ]
[A[J079 [==============================================================================>                     ]
[A[J100 [===================================================================================================>]
[Error] [LFZP] failed to download file (-10)
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://updates-http.cdn-apple.com/2018/ios/091-74855-20180709-81396E0E-7C1C-11E8-A003-A75B544C24EB/iPhone_4.7_11.4.1_15G77_Restore.ipsw

Build 15G77 for device iPhone8,1 IS NOT being signed!

**Comment by nicovell3** [comment]
Hello,

I think this issue came again since IOS 13. I can download any IOS 12 or previous blob, but with IOS 13 this tool gives me always the same error:

```
[root@2fada6b128a6 ~]# LD_PRELOAD=libcurl.so.3 tsschecker -d iPhone9,4 --ios 13.1.3 --nocache
tsschecker: /usr/lib/libcurl.so.3: no version information available (required by tsschecker)
Version: 62805e474982e78d378fea023c3469ffe7a5d078 - 247
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmwareurl for iOS 13.1.3 build 17A878
[TSSC] opening Buildmanifest for iPhone9,4_13.1.3_17A878
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/061-30529/29D48346-EB7A-11E9-8FDA-AB10329334FA/iPhone_5.5_P3_13.1.3_17A878_Restore.ipsw

[Error] [LFZP] failed to open url
[Error] [TSSC] ERROR: could not get BuildManifest for firmwareurl http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/061-30529/29D48346-EB7A-11E9-8FDA-AB10329334FA/iPhone_5.5_P3_13.1.3_17A878_Restore.ipsw

[Error] [TSSC] checking tss status failed!
```

**Comment by valenbg1** [comment]
Same problem as @nicovell3 (on macOS Mojave):
```
$ ./tsschecker -d iPhone8,2 -i 13.2 --nocache
Version: c0b554e83f54d39d90cac9791160bf2ccb062aed - 355
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[JSON] counting elements
[JSON] parsing elements
[TSSC] got firmware URL for iOS 13.2 build 17B84
[TSSC] opening Buildmanifest for iPhone8,2_13.2_17B84
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/041-81340/FC3F00A8-F4E5-11E9-A8C8-B6C134390AC5/iPhone_5.5_13.2_17B84_Restore.ipsw

PK00:????[Error] [LFZP] failed to open URL
[Error] [TSSC] ERROR: could not get BuildManifest for firmware URL http://updates-http.cdn-apple.com/2019FallFCS/fullrestores/041-81340/FC3F00A8-F4E5-11E9-A8C8-B6C134390AC5/iPhone_5.5_13.2_17B84_Restore.ipsw

[Error] [TSSC] checking TSS status failed!
```

**Comment by rbreaves** [comment]
Just tried it across linux, windows and macos and on the lastest 304 and going all the way back to 154 as some suggest. All of them fail.
