### ISSUE TITLE
Request SHSH for RestoreBehavior 'Update' in addition to 'Erase'

### ISSUE THREAD

**Issue by Flexperte** [tihmstar/tsschecker#56]
futurerestore supports the parameter -u / --update to switch to RestoreBehavior "Update" (Variant: Customer Upgrade Install (IPSW)). Unfortunately SHSHs saved with tsschecker cannot be used in this configuration, being reported to be created for RestoreBehavior "Erase" (Variant: Customer Erase Install (IPSW)) only. 

If there are two kinds of APtickets, it would be great if tsschecker could generate both (by option or automatically). 

Also I suggest different options to always result in different filenames, so not to accidentally overwrite a non-equivalent Ticket. Currently e.g. the in- or exclusion of baseband (by option or for other reasons) has no effect on naming.

**Comment by tihmstar** [comment]
Yes, i've been thinking on this and this is planned. 
At some point i want tsschecker to request both: erase and update ticket and save it in one file. 
By default all tools would be able to use the erase ticket, but tools like futurerestore and img4tool will get updated to also optionally pick the update ticket. 
Not sure when i'll be able to implement this though

**Comment by tihmstar** [comment]
added this feature in c816c3f28c711004e4cd75e6671ef86bdc122da7

**Comment by TwentyFour-24** [comment]
@Flexperte @tihmstar 
So since this feature was added, in case I got a SHSH file with the RestoreBehavior "Update" and I'm using futurerestore with parameter -u...

Is there a good chance to succeed with the process, when it's a major upgrade from 9.0.2 untethered to 10.2 semi-tethered?
Or is it more likely to fuck up my existing JB and having to restore to 10.2.1 afterwards?

I know this is a pretty unique and special case, still I'd be glad if you could provide me some input. Thank you in advance!

Best regards ;)

**Comment by tihmstar** [comment]
Currently futurerestore does not support this change in file format. It'd only see the restore ticket. You could manually extract the update ticket and use that, but i wouldn't recommend doing major iOS upgrades, especially from a jailbroken system. I would recommend doing a clean restore tbh.

**Comment by TwentyFour-24** [comment]
Okay thanks for clearing this. 

Cause I ended up with just that exact "Update" ticket, that @Flexperte wants to have. But I had to realize, that it's useless for a clean restore with futurerestore as I have written [here](https://github.com/tihmstar/futurerestore/issues/57).
