### ISSUE TITLE
Found an issue with getBuildidentityWithBoardconfig in tsschecker.c

### ISSUE THREAD

**Issue by r0adrunn3r42** [tihmstar/tsschecker#57]
Issue is when RestoreBehavior is Update but there is only one buildidentities dictionary.  rt was being set to NULL, which then the function would return NULL.  Fixed code:

if ((strncmp(string, "Erase", strlen(string)) != 0) == !isUpdateInstall){
            //continue when Erase found but isUpdateInstall is true
            //or Update found and isUpdateInstall is false
            
            //@fix
            //dont set rt to NULL because if there is only one build entity
            //null will be returned from the function
            //rt = NULL;
            continue;
        }

hope it helps, great tool!

**Comment by tihmstar** [comment]
I admit the code is quite complex and ugly. 
But i don't really understand what the problem here is.
In case i want to select the Erase behavior but Update is the only entry, then the expected behaviour would be to return NULL, because no matching identity was found. 

Do you have a testcase maybe which demonstrates the bug you're trying to fix?
Like a specific BuildManifest file or maybe a hand crafted one for example?

**Comment by r0adrunn3r42** [comment]
Correct but the code says if its != "Erase" return null.  In my Case it was returning "Update" and that was the only entry so null was returned.

Does that make sense?

I think this is the BuildBanifest.
[iPad5,2_10.2.1ota.txt](https://github.com/tihmstar/tsschecker/files/756409/iPad5.2_10.2.1ota.txt)

**Comment by r0adrunn3r42** [comment]
When I made the change the ota updater worked for me.

**Comment by tihmstar** [comment]
So i just looked into this. The problem you reported is not actually a bug.
The problem was that tsschecker tries to request an APTicket for erase install by default.
Since it can't find an erase install configuration in the ota buildmanifest you specified, it returns this error (which makes sense since ota updates are supposed to be "update" rather than "erase" installs). Therefore the code works as intended.

Nevertheless you probably still want to get an APTicket for this configuration, even though it's not an erase install. That's why i added an option -u (or --update-install) to tsschecker dfffe00354aaad14f50cecb931eb4fd70599db3a as well as made it fallback to the alternative install configuration by default, in case the default config wasn't found and the user did not select a config manually.
I think this update should fit your usecase :)
