### ISSUE TITLE
Can't Grab iPhone 5S (iPhone6,1 & iPhone6,2) noNonce Blobs

### ISSUE THREAD

**Issue by OothecaPickle** [tihmstar/tsschecker#84]
https://ghostbin.com/paste/q8z3w

**Comment by 0neday** [comment]
@OothecaPickle  yeah, I set  devVals->apnonce = NULL on line 867 tsschecker.c, and get it work, but that is fake noNonce Blobs, I also try to set devVals->apnonce = arbitrarily not zero value, but... doesn't work for iPhone5s

**Comment by 0neday** [comment]
@OothecaPickle  maybe you could find difference from [savethemblob](https://github.com/0neday/savethemblobs), I use this to get noNonce for iPhone 5S

**Comment by OothecaPickle** [comment]
Alright, so here's what I've figured out:

When grabbing iPhone9,1 blobs, the UUID entry in the TSS request remains the same when grabbing Erase blobs WITH a nonce and Erase blobs WITHOUT a nonce.

However, when grabbing iPhone6,1 blobs, the UUID entry in the TSS request is different when grabbing Erase blobs WITH a nonce and Erase blobs WITHOUT a nonce.

I hope this is something to go on @tihmstar :) I really hope to see this issue get fixed soon.

**Comment by bigrck64** [comment]
@OothecaPickle Do you know if any old version of tsschecker is working well for iPhone5s ?
I try built v170 and your fork, but any of them seems to be ok

**Comment by OothecaPickle** [comment]
@tihmstar any news on the root cause of this?

**Comment by zweed4u** [comment]
As an owner of a 5S GSM (6,1) I have noticed this as well. Again, I can confirm it is exclusive to certain devices as I also tested with a 7 GSM (9,3) and did not get this issue after the 2-3 successful request attempts. 

I have a few questions as well: 
- Would this infringe upon the success of futurerestore124 on this device? I am using tsschecker232 as the version of this dependency.
- In addition, can we adjust the urls in the array to just exclude these?

**Comment by tihmstar** [comment]
I put the noNonce feature in to get aptickets without a nonce for 32bit device, which then can be exploit the bug in iOS 9 which doesn't complain about the nonce, if it doesn't exist.
Using this method it is possible to restore iOS 9 on 32bit devices without jailbreak etc.
And since there *might* be more cool stuff which one could do with that in future i just added that.
This was never ment to be a feature for 64bit device, but after playing a bit around i realized that if sending an empty nonce (instead of no Apnonce at all, like on 32bit) one would get an apticket for 64bit devices. Currently there are no publicly known ways to make any use of that, but maybe in future?

I have tested this with iPhone6,2 and since it worked i left that in. I haven't really changed anything there since, so i belive apple simple patched their tss servers and simply not giving out aptickets with an empty ApNonce anymore.
I can remove tha for 64bit device since it doesn't work anyways now, to save a few seconds when grabbing blobs, or i can just leave that in so that if one day apple breaks stuff and it magically works again, it'll grab us the tickets.

So basically that's not a bug in tsschecker, but rather a bug in tss servers, which apple seems to have fixed.
